name: CI-CD + Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # -------------- ANALISIS ESTATICO DEL DOCKERFILE -----------------
    - name: Run Trivy on Dockerfile (Static Analysis)
      uses: aquasecurity/trivy-action@0.12.0
      with:
        scan-type: 'config'
        scan-ref: './Dockerfile'

    # -------------- LOGIN A DOCKER HUB -----------------
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    # -------------- BUILD DE LA IMAGEN -----------------
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/wordpress-azure-ci-cd:latest .

    # -------------- ANALISIS DE VULNERABILIDADES DEL CONTENEDOR --------
    - name: Run Trivy on built image
      uses: aquasecurity/trivy-action@0.12.0
      with:
        image-ref: ${{ secrets.DOCKER_USER }}/wordpress-azure-ci-cd:latest
        format: 'table'

    # -------------- PUSH A DOCKER HUB ---------------
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/wordpress-azure-ci-cd:latest
