name: CI-CD + Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # --------- ANALISIS ESTATICO DEL DOCKERFILE -----------
    - name: Run Trivy on Dockerfile
      uses: aquasecurity/trivy-action@0.12.0
      with:
        scan-type: 'config'
        scan-ref: './Dockerfile'

    # --------- LOGIN EN DOCKER HUB -------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    # --------- BUILD DE LA IMAGEN --------------------------
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/wordpress-azure-ci-cd:latest .

    # --------- ANALISIS DE VULNERABILIDADES (IMAGEN) -------
    - name: Scan built image with Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
        image-ref: ${{ secrets.DOCKER_USER }}/wordpress-azure-ci-cd:latest
        format: 'table'

    # --------- PUSH A DOCKER HUB ---------------------------
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/wordpress-azure-ci-cd:latest
